---
title: Bag of Tricks in data.table
author: Qiushi Yan
date: '2021-09-02'
slug: []
categories: []
tags: []
summary: "Tricks in R's data.table package"
lastmod: '2021-09-02T15:39:33-05:00'
draft: yes
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  collapse = TRUE,
  comment = "#>", 
  fig.align = "center"
)
```


```{r}
library(data.table)
```

[friends](https://github.com/EmilHvitfeldt/friends) package

```{r}
dt <- as.data.table(friends::friends_info)
dt
```


# Change in Place: the reference semantics 

# Special Symbols

## .N 

## .SD and .SDcols 

```{r}
dt[, lapply(.SD, mean), season, .SDcols = c("imdb_rating", "us_views_millions")]
```


# Using keys and index 

```{r}

```



# Tidy Data

- `melt(data, id.vars, measure.vars, variable.name = "variable", value.name = "value")`: wide to long

- `dcast(data, formula, value.var)`: long to wide 

```{r}
bil <- as.data.table(tidyr::billboard)
bil
```


```{r}
bil_long <- melt(bil, measure.vars = patterns("^wk"), 
                 variable.name = "week", value.name = "ranking")
bil_long
```


```{r}
dcast(bil_long, ... ~ week, value.var = "ranking")
```



# data.table's Miscellaneous Functions 

`copy`

`patterns`
