graph TB
A(Deploy with Firebase: the workflow)-->B(firebase-deploy: the job)
A(Deploy with Firebase: the workflow)-->C(other potential jobs)
B(firebase-deploy: the job)-->D(when to run? when pushing to the dev branch)
B(firebase-deploy: the job)-->E(on which system? the latest ubuntu system)
B(firebase-deploy: the job)-->F(what to do? the steps)
F(what to do?)-->G(use actions/checkout: Get all the files inside the repo)
G(use actions/checkout: Get all the files inside the repo)-->H(use actions/setup-node: Install node.js as well as npm)
H(use actions/setup-node: Install node.js as well as npm)-->I(run npm install: Install project dependencies)
I(run npm install: Install project dependencies)-->J(run npm run build: build and update the site)
J(run npm run build: build and update the site)-->K(use w9jds/firebase-action: Let Firebase to host the updated site)
classDef className font-size:18.5px, text-align:left;
class A,B,C,D,E,F,G,H,I,J,K className;